version: '2'
services:
  dwy:
    build: .  
    expose:
      - "3000"
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  lb:
    image: dockercloud/haproxy
    links:
      - dwy:dwy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:3000
