nginx:
  build: ./nginx
  links:
    - dwy:dwy
  ports:
    - "80:80"
  volumes:
    - /etc/nginx/psw:/etc/nginx/psw
    - /etc/nginx/ssl:/etc/nginx/ssl
  environment:
    - DOMAIN_NAME=brokenhand
dwy:
  build: .
  ports:
    - "3000"
  volumes:
    - /tmp:/tmp
  environment:
    - MODE=dev
    - CLOUDWATCH_REGION=us-west-2
