version: '2'
services:
  dwy:
    build: .
    expose:
      - "3000"
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  lb:
    image: dockercloud/haproxy
    depends_on:
      - dwy
    environment:
      - ADDITIONAL_SERVICES=project_dir:web,project_dir:blog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80