version: '2'
services:
  dwy:
    build: .
    ports:
      - "3000-3004:3000"
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  lb:
    image: dockercloud/haproxy
    depends_on:
      - dwy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:3000