version: '2'
services:
  dwy:
    build: .
    expose:
      - "3000"
      - "3001"
      - "3002"
      - "3003"
      - "3004"
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  lb:
    image: dockercloud/haproxy
    depends_on:
      - dwy
    environment:
      - MODE=tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
