version: '2'
services:
  dwy:
    build: .
    ports:
      - "3000-3004"
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  lb:
    image: dockercloud/haproxy
    depends_on:
      - dwy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVICE_PORTS: 3000
    ports:
      - 80:80
